AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda -> SQS -> Lambda

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  # Define the SQS topic
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DeadLetterSQSQueue" 
            - "Arn"
        maxReceiveCount: 3
  DeadLetterSQSQueue: 
    Type: AWS::SQS::Queue      

  # Define Worker Lambda Function
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: worker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue.Arn
            ScalingConfig:
              MaximumConcurrency: 5

  # Define Producer Lambda Function
  ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: producer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Environment:
        Variables:
          QUEUE_URL: !Ref SQSQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSQueue.QueueName